name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 19 UTC everyday
    - cron: "0 19 * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: Image ALT
          IMG_PATH: images
          IMG_REPOSITORY: DenverCoder1/minimalistic-wallpaper-collection
