name: create wallpaper

on:
  # run automatically every day
  schedule:
    - cron: "0 0 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-daily-wallpaper.jpg
        # uses: actions/checkout@v3
        uses: valitydev/action-download-file@v1
        with:
          url: https://minimalistic-wallpaper.demolab.com/?random&redirect=1
          target-path: dist/media/daily-wallpaper.jpg

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-daily-wallpaper.jpg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: media
          target_folder: media
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
