name: Download a file

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
      steps:
        - name: deploy github-daily-wallpaper.jpg
          uses: actions/checkout@v3

        - name: download github-daily-wallpaper.jpg 
          uses: valitydev/action-download-file@v1
          with:
            url: https://minimalistic-wallpaper.demolab.com/?random
            target-path: .